version: 0.2

phases:
  install:
    commands:
      - echo "No runtime install needed"
      - yum install -y openssh-clients
  pre_build:
    commands:
      - echo Decoding private key from environment variable...
      - echo $EC2_DEPLOY_KEY | base64 -d > ec2-key.pem
      - chmod 400 ec2-key.pem
  build:
    commands:
      - echo Deploying to EC2 server...
      - scp -i ec2-key.pem -o StrictHostKeyChecking=no index.php ubuntu@<EC2_PUBLIC_IP>:/var/www/html/index.php

artifacts:
  files:
    - index.php
